### ISSUE TITLE
Auto disconnect websocket on close?

### ISSUE THREAD

**Issue by AAllport** [axzae/homeassist#12]
This is more of a feature request, could we add an option to disconnect the websocket when we close the app. I'm happy to write the functionality myself if a pr would be accepted

**Comment by wizzor** [comment]
The author @axzae has indicated in the readme that he will ('most likely') go through the PRs weekly, so I my recommendation is that go ahead and write it :)

**Comment by payano** [comment]
Hello, is this still a problem, if so, can you create a new issue on: https://github.com/payano/homeassist-ng
