### ISSUE TITLE
Can't Turn Off Devices

### ISSUE THREAD

**Issue by ascillato** [axzae/homeassist#17]
Hi, I can't turn off some devices when clicking over the Icon. From the web Interface of HA I can, but on the app is like it sends only the ON command.

For example, I can turn a wifi speaker on. It change from grey icon to blue icon, but then if I press the icon again nothing happens. I can change the volume, etc, but not turn off.

From the web interface I can turn on and off.

The off option can be added?

Thanks a lot. Great app!!!!

**Comment by wayne47git** [comment]
Just tested this on a Tasmoto-firmware Sonoff device. Works properly, device goes on with one tap, off with another.

**Comment by o0Zz** [comment]
I think this issue might be related to mine:

https://github.com/axzae/homeassist/issues/24

**Comment by payano** [comment]
Hello, is this still a problem, if so, can you create a new issue on: https://github.com/payano/homeassist-ng
