### ISSUE TITLE
Migrate codebase to Kotlin(?)

### ISSUE THREAD

**Issue by markusressel** [axzae/homeassist#26]
As this is now a community driven project I'd like to hear some feedback on the idea to migrate the codebase to Kotlin as much as possible before I try and dig deep into this.

My thoughts:
Although the codebase is already pretty big IMO it would be very beneficial for future development to migrate it to Kotlin asap. Kotlin is such a great language and in many ways superiour to the old java version supported for Android development. Kotlin has great developer support and already a big collection of open source libraries for android.
I would love to contribute to this project but java lacks a lot of cool features that could make the coding life easier and its syntax is just unnecessarily complicated/bloated in comparison to kotlin.

What do you think?

**Comment by AdamLindenthal** [comment]
Hi and sorry for resurrecting a dated thread, but I just came along this.

Although I agree Kotlin looks promising and might be more comfortable to work with (once get used to), complete rework of an existing project into another JVM language would IMHO not bring benefits, that would outweight the effort and risks. 

First, this would introduce a bunch of new bugs. Yes, it might fix a few as well, if made with care, but avoiding regressions is unlikely. 

Also, the project's initial commit was pushed quite some time after Kotlin became an official Android language, so the author could have used Kotlin, but decided to go the Java way for some reason. I guess he's the one who will review the pull requests and it is beneficial if he is comfortable doing so.

Why invest such an effort into achieving the status quo - wouldn't it be better to use that energy into fixing bugs and adding features? 

I see that eight people upvoted that suggestion, so there probably might be people wanting to contribute, that won't do it as long as the project is Java-based. But given, that both JVM languages can nicely co-exist next to each other, wouldn't some smooth transition be a more reasonable way? E.g. starting with some data classes, using Kotlin for new features, but not necessarily touching everything, that already works?

Just my two cents. Anyway, glad that such project exists.

Regards,
Adam

**Comment by markusressel** [comment]
The author of this project apparently has no interest in maintaining this repo.
Since it's creation 2 PRs have been merged, both of which are simple translations. There are no comments from the author on any currently open issue and neither on one of the 4 currently open PRs.

It's a shame, since this project would be a great start, but I for one won't put any energy into this if PRs aren't even considered.

On the topic of Kotlin:
I presume you are right, the author probably has not that much experience with Kotlin otherwise he would have already converted at least some parts of the code. So even if s.o. like me were to write a PR in Kotlin it would have an even lower chance of getting merged.
