### ISSUE TITLE
Add HTTP authentication support for reverse proxies

### ISSUE THREAD

**Issue by blackwind** [axzae/homeassist#29]
My Home Assistant instance is behind a reverse proxy with HTTP authentication, and it appears this (pretty common) use case isn't currently supported, as passing a base URL with username and password (https://user:pass@192.168.2.1/) to the app returns only "Invalid Password". Looking forward to a fix.

**Comment by payano** [comment]
Hello, is this still a problem, if so, can you create a new issue on: https://github.com/payano/homeassist-ng
