### ISSUE TITLE
Tabs?

### ISSUE THREAD

**Issue by markcs** [axzae/homeassist#32]
Hi

Sorry if this is a dumb question, but how can I add a new tab to the dashboard?

Thanks!

**Comment by wizzor** [comment]
I haven't tried, but in main HA if you make a group with the type: view it will appear as tab.

I can try in a few weeks when I get my HA installation back online if you can check in the meantime please do report back.

HA docs on the subject:
https://www.home-assistant.io/components/group/

**Comment by markcs** [comment]
Nope, that doesn't work for me.... any other ideas?

**Comment by markcs** [comment]
Actually it does.  You have to log out and then log back in for the tabs to appear.
