### ISSUE TITLE
Empty dashboard

### ISSUE THREAD

**Issue by YoYoost** [axzae/homeassist#44]
Hi,

After updating a while ago I noticed that my dashboard is now empty, also I cannot add any items as that dialogue is empty.

I tried looking for another app but none work as Home Assist with the long press capabilities and not going 'full screen'

Does anyone also have this issue? Does anyone have suggestions for a similar app?

**Comment by alexdrl** [comment]
I am also having the problem. Sad to see the app discontinued.

**Comment by payano** [comment]
Hello Guys,
I have updated my Home Assistant from version 0.82.0 to 0.84.2, trying to reproduce the bug without success. My dashboard works. Can you help me out so I can reproduce this bug?

If axzae has discontinued this project, lets continue doing development on my forked branch instead.

Side note:
I have forked this project and added two pull requests besides my own. I will continue developing this app when i have time for it. I am currently developing a solution to get remote access to my home assistant at home, i want it to work seamless so you don't have to configure vpn and other stuff to get remote access to home assistant working, and i want to use the HomeAssist app as the frontend application running on my phone.

**Comment by wizzor** [comment]
Hi, I also have 0.84.2 and things seem to be working as usual. I also have my HA instance available from outside my home, works pretty seamlessly for me.
@payano should we be moving all of the discussions to your repo, rather than here? Then you can approve the pull reqs and generally control the whole process?

**Comment by payano** [comment]
@wizzor : Okay, did you open up a port on your firewall and redirect it to the homeassistant webserver? I'm not so fond of exposing internal services to the outside world. :)

Yeah, lets continue the discussion on HomeAssist-ng, in lack of a better name, suggestions are welcome, https://github.com/payano/homeassist-ng
